
package ru.javaops.masterjava.xml.schema2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailService", targetNamespace = "http://mail.javaops.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailService {


    /**
     * 
     * @param cc
     * @param subject
     * @param to
     * @param body
     */
    @WebMethod
    @RequestWrapper(localName = "sendMail", targetNamespace = "http://mail.javaops.ru/", className = "ru.javaops.masterjava.xml.schema2.SendMail")
    @ResponseWrapper(localName = "sendMailResponse", targetNamespace = "http://mail.javaops.ru/", className = "ru.javaops.masterjava.xml.schema2.SendMailResponse")
    public void sendMail(
        @WebParam(name = "to", targetNamespace = "")
        List<Addressee> to,
        @WebParam(name = "cc", targetNamespace = "")
        List<Addressee> cc,
        @WebParam(name = "subject", targetNamespace = "")
        String subject,
        @WebParam(name = "body", targetNamespace = "")
        String body);

}
